### ISSUE TITLE
Permanent delete of survey instances

### ISSUE THREAD

**Issue by scott2b** [scott2b/surveyor#2]
Allow for deletion of instances in addition to the current invalidation feature in the survey stats view.

**Comment by chrisjvargo** [comment]
Check boxes and one delete button would be preferred.

**Comment by chrisjvargo** [comment]
Looks awesome. You can push this to the production server!

Chris J. Vargo
University of Alabama
Assistant Professor, Ph.D.

Advertising & Public Relations
------------------------------

[image: Twitter] <http://www.twitter.com/chrisjvargo> [image: LinkedIn]
<http://www.linkedin.com/in/chrisjvargo> [image: Google Plus]
<https://plus.google.com/105471295838192826025> [image: WordPress]
<http://www.chrisjvargo.com/>
