### ISSUE TITLE
User ID on final page of survey should be required

### ISSUE THREAD

**Issue by scott2b** [scott2b/surveyor#3]
Don't allow users to bypass this leaving the username empty -- this should be a required field.

**Comment by chrisjvargo** [comment]
Change the response prompt from "Please enter your username" to  "Enter Your Amazon Turk Worker ID"

**Comment by scott2b** [comment]
This is already a required field in the form. It cannot be required on the survey instance because the survey instance is created earlier to handle the responses. There are a couple of things we can do:

eliminate all surveys that don't have a username. This would be easy to implement - we could have a "delete all incomplete surveys" on the stats page. The risk here is the possibility that a turker is mid-survey in which case their instance will disappear and they will probably get an error condition.

Alternatively: require the username up front instead of the end. The problem with this is that the presence of a username is no longer an indicator of survey completion.

**Comment by chrisjvargo** [comment]
Since there is no back button, how could a turker be mid survey when they
are entering their id? They should be at the end?

Chris J. Vargo
University of Alabama
Assistant Professor, Ph.D.

Advertising & Public Relations
------------------------------

[image: Twitter] <http://www.twitter.com/chrisjvargo> [image: LinkedIn]
<http://www.linkedin.com/in/chrisjvargo> [image: Google Plus]
<https://plus.google.com/105471295838192826025> [image: WordPress]
<http://www.chrisjvargo.com/>

**Comment by scott2b** [comment]
The ID is at the end. It is the last thing to submit after all responses.

**Comment by chrisjvargo** [comment]
Right, so I think option #1 works. I don't understand how "a turker is
mid-survey in which case their instance will disappear" if they are
entering the ID at the end

Chris J. Vargo
University of Alabama
Assistant Professor, Ph.D.

Advertising & Public Relations
------------------------------

[image: Twitter] <http://www.twitter.com/chrisjvargo> [image: LinkedIn]
<http://www.linkedin.com/in/chrisjvargo> [image: Google Plus]
<https://plus.google.com/105471295838192826025> [image: WordPress]
<http://www.chrisjvargo.com/>

**Comment by scott2b** [comment]
Oh, the instance is created when you start a survey, not finish it. This is necessary because the responses need to be attached to an instance. So if there are 5 pages in a survey and somebody is on page 3, they have not entered their ID yet -- so if we delete all instances with blank IDs then the instance they are working on will disappear. When they submit page 3 to go to page 4, my guess is that there will be a key error.

**Comment by chrisjvargo** [comment]
OK - That makes sense.

Can we create a condition like this?

If an instance is over two hours old:
    If a instance has a blank username:
       delete instance

Chris J. Vargo
University of Alabama
Assistant Professor, Ph.D.

Advertising & Public Relations
------------------------------

[image: Twitter] <http://www.twitter.com/chrisjvargo> [image: LinkedIn]
<http://www.linkedin.com/in/chrisjvargo> [image: Google Plus]
<https://plus.google.com/105471295838192826025> [image: WordPress]
<http://www.chrisjvargo.com/>

**Comment by chrisjvargo** [comment]
Alternative idea that may be easier. What if we changed the reporting in
the stats page?

Filter out blank usernames from reporting here:
http://surveyor.beta.codeslick.com/survey/1/stats

Filter out everything but blank usernames here:
http://surveyor.beta.codeslick.com/survey/1/blanks

I'll go through and manually delete blanks from time to time.

Chris J. Vargo
University of Alabama
Assistant Professor, Ph.D.

Advertising & Public Relations
------------------------------

[image: Twitter] <http://www.twitter.com/chrisjvargo> [image: LinkedIn]
<http://www.linkedin.com/in/chrisjvargo> [image: Google Plus]
<https://plus.google.com/105471295838192826025> [image: WordPress]
<http://www.chrisjvargo.com/>

**Comment by scott2b** [comment]
We could just make it so stats and reports only include surveys with IDs. Is there a reason you ever need to see surveys without IDs?

**Comment by chrisjvargo** [comment]
What if they might fill out a couple pages of tweets and then quit, and we
don't want that data in our reports? If that data wouldn't be included,
then I think you're right.

Chris J. Vargo
University of Alabama
Assistant Professor, Ph.D.

Advertising & Public Relations
------------------------------

[image: Twitter] <http://www.twitter.com/chrisjvargo> [image: LinkedIn]
<http://www.linkedin.com/in/chrisjvargo> [image: Google Plus]
<https://plus.google.com/105471295838192826025> [image: WordPress]
<http://www.chrisjvargo.com/>
