### ISSUE TITLE
Only Report Stats of Completed Survey Instances

### ISSUE THREAD

**Issue by chrisjvargo** [scott2b/surveyor#5]
http://surveyor.codeslick.com/survey/9/stats#

You'll see a lot of turkers start a survey and then bail, thinking it is too hard. Can only report stats/results for surveys that go all the way through the end, enter their turk ID, then click submit?

**Comment by scott2b** [comment]
related to #3. Once we have user IDs required, we can filter out any surveys that don't have a user ID, which is indicative of not fully submitting all survey pages.
