### ISSUE TITLE
End of Survey - Change to Generate Randomly Generated Alphanumeric String

### ISSUE THREAD

**Issue by chrisjvargo** [scott2b/surveyor#8]
Turkers are manipulating the current set up we have. Basically they're not doing the survey and saying they did. So we need to make them provide evidence that they are indeed doing it. 

At the end of the survey, instead of having a user enter the WorkerID, we will need to generate a random 7 digit alphanumeric string. The instructions on that page should read
"Thank you for completing the survey. To be paid, please take the participation code below and enter submit it with your HIT on Amazon Turk. If you do not submit this correct code, you will not be paid."

This randomly generated code should be stored in place of where we have the workerIDs now in the stats page for each survey. 

<img width="295" alt="screen shot 2015-09-21 at 9 36 16 am" src="https://cloud.githubusercontent.com/assets/2052838/9994736/4fe98f2e-6044-11e5-9c3c-b65e8a8f33c8.png">

This way we can verify who actually did the survey and who did not.

**Comment by scott2b** [comment]
Do we need to capture both the Turk ID and the random ID? If we just need the random ID, I can populate the username field with the random string and be done with it. If we need both, it will take just a bit more work to add the extra field to the model, etc. Let me know which seems right.

**Comment by chrisjvargo** [comment]
Just the random ID. Do not need both!

Chris J. Vargo
University of Alabama
Assistant Professor, Ph.D.

Advertising & Public Relations
------------------------------

[image: Twitter] <http://www.twitter.com/chrisjvargo> [image: LinkedIn]
<http://www.linkedin.com/in/chrisjvargo> [image: Google Plus]
<https://plus.google.com/105471295838192826025> [image: WordPress]
<http://www.chrisjvargo.com/>

**Comment by scott2b** [comment]
Done
